sudo: required
language: erlang
otp_release:
  - 19.3
  - 18.3
  - 17.3
  - R16B03
  - R15B03
  - R14B04
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq ${EMACS}
  - emacs -Q --batch -L ${PWD} -l test/package-install-deps.el
script:
  - "make -s test"
